services:
  macos:
    image: dockurr/macos:2.12
    container_name: macos
    environment:
      VERSION: "14"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - /docker/appdata/macos:/storage
    restart: always
    stop_grace_period: 2m