---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: monitoring

    controllers:
      loki:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          loki:
            image:
              repository: grafana/loki
              tag: 3.5.4
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
            args:
              - "-config.file=/etc/loki/loki-config.yml"
            probes:
              liveness:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 150Mi
              limits:
                memory: 256Mi

    service:
      app:
        primary: true
        controller: loki
        type: LoadBalancer
        ports:
          http:
            port: 3100

    # ingress:
    #   internal:
    #     enabled: true
    #     className: nginx
    #     hosts:
    #       - host: "loki.${LOCAL_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               identifier: app
    #               port: http
    #     tls:
    #       - hosts:
    #           - "loki.${LOCAL_DOMAIN}"
    #         secretName: local-mafyuh-dev-production-tls

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
        globalMounts:
          - path: /etc/loki
      
      loki-config:
        enabled: true
        type: configMap
        name: loki-config
        defaultMode: 0400
        globalMounts:
          - path: /etc/loki/loki-config.yml
            subPath: loki-config.yml
