# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: flux-operator
      version: 0.32.0
      sourceRef:
        kind: HelmRepository
        name: controlplaneio
        namespace: flux-system
  dependsOn: []
  values:
    serviceMonitor:
      create: true