---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app code-server
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: code-server
  values:
    global:
      fullnameOverride: *app
      namespace: default

    controllers:
      code-server:
        enabled: true
        type: deployment

        replicas: 1

        containers:
          app:
            image:
              repository: mirror.gcr.io/binhex/arch-code-server
              tag: 4.117
              pullPolicy: IfNotPresent
            env:
              SELF_SIGNED_CERT: "no"
              ENABLE_STARTUP_SCRIPTS: "yes"
              CERT_PATH: ""
              CERT_KEY_PATH: ""
              UMASK: "002"
              PUID: "1000"
              PGID: "1000"
              PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: code-server-secret
                    key: PASSWORD

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
                  - DAC_OVERRIDE
                  - FOWNER

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      app:
        primary: true
        controller: code-server
        ports:
          http:
            port: &port 8500

    route:
      internal:
        enabled: true
        kind: HTTPRoute
        hostnames: ["c.mafyuh.dev"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: code-server
                port: *port
        parentRefs:
          - name: envoy-external
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
        globalMounts:
          - path: /config
      data:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi
        retain: true
        globalMounts:
          - path: /data
      home:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 3Gi
        retain: true
        globalMounts:
          - path: /home