---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
name: ollama
services:
  searxng:
    image: searxng/searxng@sha256:2008614c3dfba2baf7971503a8680a9799c59b144a3d9675b5f985d68917472b
    container_name: searxng
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/searxng:/etc/searxng
    restart: unless-stopped
    ports:
      - "8081:8080"

  open-terminal:
    container_name: open-terminal
    image: ghcr.io/open-webui/open-terminal:0.11.34
    restart: unless-stopped
    ports:
      - 3001:8000
    volumes:
      - open-terminal:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=$OPEN_TERMINAL_API_KEY

  mcphub:
    container_name: mcphub
    image: mirror.gcr.io/samanhappy/mcphub:1.0.13
    restart: unless-stopped
    ports:
      - 3003:3000
    environment:
      - ADMIN_PASSWORD=$MCPHUB_ADMIN_PASSWORD
    volumes:
      - ./mcp_settings.json:/app/mcp_settings.json:rw

  cli-proxy-api:
    container_name: cli-proxy-api
    image: mirror.gcr.io/eceasy/cli-proxy-api:v7.1.74
    restart: unless-stopped
    ports:
      - 8317:8317
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - /docker/appdata/cli-proxy-api/auth-dir:/root/.cli-proxy-api

volumes:
  open-terminal: