---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.2.0
    labels:
      komodo.skip:
    restart: unless-stopped
    init: true
    environment:
      PERIPHERY_ROOT_DIRECTORY: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      PERIPHERY_CORE_ADDRESS: komo.mafyuh.io
      PERIPHERY_CONNECT_AS: ${PERIPHERY_CONNECT_AS}
      PERIPHERY_ONBOARDING_KEY: ${PERIPHERY_ONBOARDING_KEY}
      PERIPHERY_SSL_ENABLED: true
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_CORE_PUBLIC_KEYS: MCowBQYDK2VuAyEAdaEppEhX6hboF6Tt1SiCoGiiCe35BYbc1FrG+PRVCU8=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
    ports:
      - 8120:8120
