services:
  plex:
    image: ghcr.io/linuxserver/plex@sha256:d4ea24c1f42d36f3c5ee485418a746be0440fe3c2b735c162c15d028f3495a6f
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /docker/appdata/plex/library:/config
      - nas:/data/media
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  nas:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.lan,vers=4,ro
      device: ":/mnt/thePool/thePoolShare/Media"
