---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd-exporter
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    global:
      fullnameOverride: sabnzbd-exporter
      namespace: arr

    controllers:
      sabnzbd-exporter:
        enabled: true
        type: deployment
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0
              pullPolicy: IfNotPresent
            env:
              PORT: &metricsPort 9707
              URL: "https://sab.mafyuh.xyz"
              APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: recyclarr-secrets
                    key: SABNZBD_API_KEY
            args: ["sabnzbd"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      app:
        primary: true
        controller: sabnzbd-exporter
        ports:
          metrics:
            port: *metricsPort

    serviceMonitor:
      main:
        enabled: true
        serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}'
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s