---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      radarr:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1
        
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.0.0.10217
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              RADARR__INSTANCE_NAME: *app
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: "https://radarr.${LOCAL_DOMAIN}"
              RADARR__THEME: dark
              RADARR__LOG_LEVEL: info

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 50m
                memory: 150Mi
              limits:
                memory: 512Mi

          metrics:
            dependsOn: app
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}-app.{{ .Release.Namespace }}.svc.cluster.local:7878"
              APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: recyclarr-secrets
                    key: RADARR_API_KEY
            args: ["radarr"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      app:
        primary: true
        controller: radarr
        ports:
          http:
            port: *port
      metrics:
        controller: radarr
        ports:
          metrics:
            port: *metricsPort
    
    serviceMonitor:
      main:
        enabled: true
        serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-metrics'
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      internal:
        enabled: true
        kind: HTTPRoute
        hostnames: ["{{ .Release.Name }}.local.mafyuh.dev"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: radarr-app
                port: *port
          - matches:
              - path:
                  type: PathPrefix
                  value: /metrics
            backendRefs:
              - name: radarr-metrics
                port: *metricsPort
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 3Gi
        storageClass: longhorn
        globalMounts:
          - path: /config

      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data
