---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  nginx:
    image: mirror.gcr.io/jc21/nginx-proxy-manager:2.15.1
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /docker/appdata/nginx/data:/data
      - /docker/appdata/nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  fail2ban:
    image: ghcr.io/crazy-max/fail2ban:1.1.0
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/docker/appdata/fail2ban/data:/data"
      - "/var/log/auth.log:/var/log/auth.log:ro"
      - "/docker/appdata/nginx/data/logs/:/log/npm/:ro"
      - "/docker/appdata/fail2ban/f2b-logs:/f2b-logs:rw"
    environment:
      - TZ=America/New_York
      - F2B_LOG_TARGET=/f2b-logs/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d
      - F2B_MAX_RETRY=3
      - SSMTP_HOST=$SSMTP_HOST
      - SSMTP_PORT=587
      - SSMTP_HOSTNAME=$SSMTP_HOSTNAME
      - SSMTP_USER=$SSMTP_USER
      - SSMTP_PASSWORD=$SSMTP_PASSWORD
      - SSMTP_TLS=YES
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: unless-stopped

  cf-tunnel:
    restart: unless-stopped
    image: mirror.gcr.io/cloudflare/cloudflared@sha256:b269e8abd07a5bf6f3f4be65d5050b2174eca89c56a0241a8ff32a16aec454e4
    command: tunnel --no-autoupdate run --token $CF_TOKEN
    container_name: cloudflared

  tailscale:
    image: tailscale/tailscale:v1.102.3
    container_name: tailscale
    hostname: npm-subnet-router
    entrypoint:
      - sh
      - -c
      - ln -sf /usr/sbin/iptables-nft /usr/sbin/iptables && ln -sf /usr/sbin/ip6tables-nft /usr/sbin/ip6tables && exec /usr/local/bin/containerboot
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_HOSTNAME=npm-subnet-router
      - TS_ROUTES=10.69.69.0/24,10.20.10.0/24,10.0.0.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    restart: unless-stopped

volumes:
  tailscale-data:
