---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: flux-system
      version: 1.10.0
  interval: 1m0s
  values:
    defaultSettings:
      defaultLonghornStaticStorageClass: longhorn
    defaultBackupStore:
      backupTarget: s3://longhorn@us-east-1/
      backupTargetCredentialSecret: longhorn-s3-secret
