---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  gotify:
    image: ghcr.io/gotify/server:2.9.1
    container_name: gotify
    volumes:
      - /docker/appdata/gotify:/app/data
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - GOTIFY_DEFAULTUSER_NAME=$GOTIFY_DEFAULTUSER_NAME
      - GOTIFY_DEFAULTUSER_PASS=$GOTIFY_DEFAULTUSER_PASS
    networks:
      - racknerd

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.14.0
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 127.0.0.1:81:81
      - 443:443
    volumes:
      - /docker/appdata/nginx/data:/data
      - /docker/appdata/nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - racknerd

  fail2ban:
    image: crazymax/fail2ban:1.1.0
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/docker/appdata/fail2ban/data:/data"
      - "/var/log/auth.log:/var/log/auth.log:ro"
      - "/docker/appdata/nginx/data/logs/:/log/npm/:ro"
      - "/docker/appdata/fail2ban/f2b-logs:/f2b-logs:rw"
    environment:
      - TZ=America/New_York
      - F2B_LOG_TARGET=/f2b-logs/fail2ban.log
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d
      - F2B_MAX_RETRY=3
      - SSMTP_HOST=$SSMTP_HOST
      - SSMTP_PORT=587
      - SSMTP_HOSTNAME=$SSMTP_HOSTNAME
      - SSMTP_USER=$SSMTP_USER
      - SSMTP_PASSWORD=$SSMTP_PASSWORD
      - SSMTP_TLS=YES
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    restart: unless-stopped

  n8n:
    image: ghcr.io/n8n-io/n8n:2.19.2
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - WEBHOOK_URL=$WEBHOOK_URL
    restart: unless-stopped
    networks:
      - racknerd

  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.36.0
    container_name: vaultwarden
    volumes:
      - /home/mafyuh/vw-data/:/data
    environment:
      - DOMAIN=$VWDOMAIN
      - SIGNUPS_ALLOWED=true
      - SSO_ENABLED=true
      - SSO_AUTHORITY=https://auth.mafyuh.io/application/o/vaultwarden/
      - SSO_SCOPES="openid email profile offline_access"
      - SSO_ONLY=true
      - SSO_AUTH_ONLY_NOT_SESSION=true
      - SSO_CLIENT_ID=e17019c548f26f15e483b74b2b0a95e8900a03bb
      - SSO_CLIENT_SECRET=$SSO_CLIENT_SECRET
      - SMTP_HOST=smtp.protonmail.ch
      - SMTP_FROM=noreply@mafyuh.dev
      - SMTP_FROM_NAME=Vaultwarden
      - SMTP_USERNAME=noreply@mafyuh.dev
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_TIMEOUT=15
      - SMTP_SECURITY=starttls
      - SMTP_PORT=587
      - DATABASE_URL=$DATABASE_URL
    restart: unless-stopped
    networks:
      - racknerd

  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vaultwarden
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vaultwarden
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - racknerd

networks:
  racknerd:
    external: true

volumes:
  linkstack:
  n8n_data:
  postgres_data:
