---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  pegaprox:
    image: ghcr.io/pegaprox/pegaprox:0.9.7
    container_name: pegaprox
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - pegaprox-config:/app/config
      - pegaprox-logs:/app/logs
    restart: unless-stopped
    environment:
      PEGAPROX_BEHIND_PROXY: "true"
      PEGAPROX_TRUSTED_PROXIES: "192.168.2.0/16"
      PEGAPROX_ALLOWED_ORIGINS: "https://pegaprox.mafyuh.xyz"

volumes:
  pegaprox-config:
  pegaprox-logs: