# Site-to-site access from the home UniFi networks to the private OKE endpoint,
# worker subnet, and private service load balancers.

resource "oci_core_cpe" "home" {
  compartment_id      = data.bitwarden-secrets_secret.compartment_ocid.value
  display_name        = "unifi-dream-router-home-new-ip"
  ip_address          = data.bitwarden-secrets_secret.homelab_ip.value
  cpe_device_shape_id = "0c14a129-ce70-43f3-bf07-e980a6784ae8"
}

resource "oci_core_drg" "oke" {
  compartment_id = data.bitwarden-secrets_secret.compartment_ocid.value
  display_name   = "oke-vcn-lan-drg"
}

resource "oci_core_drg_route_distribution" "all_routes" {
  drg_id            = oci_core_drg.oke.id
  display_name      = "Autogenerated Import Route Distribution for ALL routes"
  distribution_type = "IMPORT"
}

resource "oci_core_drg_route_distribution" "vcn_routes" {
  drg_id            = oci_core_drg.oke.id
  display_name      = "Autogenerated Import Route Distribution for VCN Routes"
  distribution_type = "IMPORT"
}

resource "oci_core_drg_route_table" "vcn_attachments" {
  drg_id                           = oci_core_drg.oke.id
  display_name                     = "Autogenerated Drg Route Table for VCN attachments"
  import_drg_route_distribution_id = oci_core_drg_route_distribution.all_routes.id
  is_ecmp_enabled                  = false
}

resource "oci_core_drg_route_table" "ipsec_attachments" {
  drg_id                           = oci_core_drg.oke.id
  display_name                     = "Autogenerated Drg Route Table for RPC, VC, and IPSec attachments"
  import_drg_route_distribution_id = oci_core_drg_route_distribution.vcn_routes.id
  is_ecmp_enabled                  = false
}

resource "oci_core_drg_attachment" "oke_vcn" {
  drg_id             = oci_core_drg.oke.id
  display_name       = "oke-vcn-lan-drg-attachment"
  drg_route_table_id = oci_core_drg_route_table.vcn_attachments.id
  vcn_id             = oci_core_vcn.oke.id

  network_details {
    id             = oci_core_vcn.oke.id
    type           = "VCN"
    vcn_route_type = "SUBNET_CIDRS"
  }
}

resource "oci_core_ipsec" "home" {
  compartment_id            = data.bitwarden-secrets_secret.compartment_ocid.value
  display_name              = "oke-vcn-lan-to-unifi-new-ip"
  cpe_id                    = oci_core_cpe.home.id
  drg_id                    = oci_core_drg.oke.id
  cpe_local_identifier      = data.bitwarden-secrets_secret.homelab_ip.value
  cpe_local_identifier_type = "IP_ADDRESS"
  static_routes             = var.home_network_cidrs
}
