services:
  nexterm:
    container_name: nexterm
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.3-OPEN-PREVIEW

  it-tools:
    container_name: it-tools
    ports:
      - 8090:80
    image: corentinth/it-tools@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    restart: unless-stopped

volumes:
  nexterm:
