---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: oke-cluster
  namespace: databases
spec:
  postgresVersion: 18
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        pg_hba:
          - "local all all trust"
          - "host all all 127.0.0.1/32 md5"
          - "host all all ::1/128 md5"
          - "local replication standby trust"
          - "hostssl replication standby all md5"
          - "host all all 10.244.0.0/16 md5"
          - "host all all 0.0.0.0/0 md5"
          - "hostssl all all 0.0.0.0/0 md5"
        parameters:
          shared_buffers: "256MB"
          effective_cache_size: "768MB"
          maintenance_work_mem: "192MB"
          checkpoint_completion_target: "0.9"
          wal_buffers: "16MB"
          default_statistics_target: "100"
          random_page_cost: "1.1"
          effective_io_concurrency: "200"
          work_mem: "4MB"
          min_wal_size: "2GB"
          max_wal_size: "8GB"
          max_worker_processes: "4"
          max_parallel_workers_per_gather: "2"
          max_parallel_workers: "4"
          max_connections: "600"
          synchronous_commit: "on"
  instances:
    - name: oke-pg-cluster
      replicas: 2
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: oke-cluster
                  postgres-operator.crunchydata.com/instance-set: oke-pg-cluster
      dataVolumeClaimSpec:
        storageClassName: oci-bv
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  users:
    - name: mafyuh
      options: "SUPERUSER"
    - name: vaultwarden
      databases:
        - vaultwarden
    - name: gotify
      databases:
        - gotify
    - name: n8n
      databases:
        - n8n
    - name: forgejo
      databases:
        - forgejo
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: oke-cluster-crunchy-postgres
      global:
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /oke-cluster
        repo1-retention-full: "7"
        repo1-retention-full-type: time
        repo1-s3-uri-style: path
      jobs:
        ttlSecondsAfterFinished: 60
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: postgres
            endpoint: "https://s3.mafyuh.xyz"
            region: us-east-1
          schedules:
            full: "30 0 * * *"
