---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:832305698a608905bfae7236712305dc73aab6d440d76939e94e358d80191d92
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
