---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:898596ace748635fb27e04a8b2a12deaa03b87e607d82919f6e9966d945a3b24
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
