---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      prowlarr:
        enabled: true
        type: deployment


        replicas: 1
        
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.1.3.5208
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              PROWLARR__INSTANCE_NAME: *app
              PROWLARR__PORT: &port 9696
              PROWLARR__APPLICATION_URL: "https://prowlarr.${LOCAL_DOMAIN}"
              PROWLARR__THEME: dark
              PROWLARR__LOG_LEVEL: info
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: recyclarr-secrets
                    key: PROWLARR_API_KEY

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 50m
                memory: 150Mi
              limits:
                memory: 512Mi
          
          metrics:
            dependsOn: app
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}-app.{{ .Release.Namespace }}.svc.cluster.local:9696"
              APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: recyclarr-secrets
                    key: PROWLARR_API_KEY
            args: ["prowlarr"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      app:
        primary: true
        controller: prowlarr
        ports:
          http:
            port: *port
      metrics:
        controller: prowlarr
        ports:
          metrics:
            port: *metricsPort
    
    serviceMonitor:
      main:
        enabled: true
        serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-metrics'
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      internal:
        enabled: true
        kind: HTTPRoute
        hostnames: ["{{ .Release.Name }}.local.mafyuh.dev"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: prowlarr-app
                port: *port
          - matches:
              - path:
                  type: PathPrefix
                  value: /metrics
            backendRefs:
              - name: prowlarr-metrics
                port: *metricsPort
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn
        globalMounts:
          - path: /config

      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data
