---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    global:
      fullnameOverride: *app
      namespace: monitoring

    controllers:
      unpoller:
        enabled: true
        type: deployment


        replicas: 1

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"
        
        containers:
          unpoller:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.15.4
              pullPolicy: IfNotPresent
            env:
              UP_UNIFI_DEFAULT_PASS: ${UP_UNIFI_DEFAULT_PASS}
              UP_UNIFI_DEFAULT_USER: "unifipoller"
              UP_UNIFI_DEFAULT_URL: "https://10.20.10.1"
              UP_INFLUXDB_DISABLE: true
        
            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            
            resources:
              requests:
                cpu: 100m
                memory: 150Mi
              limits:
                memory: 256Mi
        
    service:
      unpoller:
        enabled: true
        type: ClusterIP
        ports:
          metrics:
            port: 9130

    serviceMonitor:
      main:
        enabled: true
        serviceName: "unpoller"
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s