---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui-secrets
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: OPENAI_API_KEYS
      remoteRef:
        key: "7bb7c8f6-cff8-4376-9b16-b44d001faec8"
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: "876c897e-46ba-4e80-aa8c-b3ee018293b6"
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: "070a254e-dcac-45b5-b815-b3ee0180a339"
    - secretKey: DATABASE_URL
      remoteRef:
        key: "4f53b805-b2d7-45d6-ae5b-b43a0039a86b"
