---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: optiplex-k8s
endpoint: https://10.0.0.150:6443
# renovate: depName=siderolabs/talos datasource=github-releases
talosVersion: v1.14.0
# renovate: depName=kubernetes/kubernetes datasource=github-releases
kubernetesVersion: v1.37.0
additionalApiServerCertSans: &sans
  - 127.0.0.1
additionalMachineCertSans: *sans
cniConfig:
  name: none
nodes:
  - hostname: talos-4
    ipAddress: 10.0.0.201
    controlPlane: true
    installDisk: /dev/disk/by-id/nvme-eui.36483330542821510025385800000001
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: e8:6a:64:bf:bf:10
        dhcp: true
        vip:
          ip: &vip 10.0.0.150
  - hostname: talos-5
    ipAddress: 10.0.0.202
    controlPlane: true
    installDisk: /dev/disk/by-id/nvme-eui.36483330542821640025385800000001
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: e8:6a:64:c8:28:e8
        dhcp: true
        vip:
          ip: *vip
  - hostname: talos-6
    ipAddress: 10.0.0.203
    controlPlane: true
    installDisk: /dev/disk/by-id/nvme-eui.36483330543292560025385800000001
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 98:fa:9b:af:65:e5
        dhcp: true
        vip:
          ip: *vip
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc
        - -selinux
        - apparmor=0
        - init_on_alloc=0
        - init_on_free=0
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off
        - security=none
        - talos.auditd.disabled=1
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/realtek-firmware
  patches:
    # Configure DNS
    - |-
      apiVersion: v1alpha1
      kind: ResolverConfig
      searchDomains:
        disableDefault: true
        domains: []
      hostDNS:
        enabled: true
        resolveMemberNames: true
        forwardKubeDNSToHost: false
    # Customize containerd (Spegel)
    - |-
      machine:
        files:
          - path: /etc/cri/conf.d/20-customization.part
            op: create
            content: |
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false
    # Allow in-cluster Talos API access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            allowedKubernetesNamespaces:
              - system-upgrade
              - actions-runner-system
            allowedRoles:
              - os:admin
            enabled: true
    # Configure cluster workload placement.
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
    # Configure kube-apiserver.
    - |-
      apiVersion: v1alpha1
      kind: KubeAPIServerConfig
      extraArgs:
        feature-gates: "ImageVolume=true,MutatingAdmissionPolicy=true,ResourceHealthStatus=true"
        runtime-config: "admissionregistration.k8s.io/v1beta1=true"
    # Cilium replaces kube-proxy.
    - |-
      apiVersion: v1alpha1
      kind: KubeProxyConfig
      enabled: false
    # Configure etcd
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 10.0.0.0/24
    # Configure kube-controller-manager metrics
    - |-
      apiVersion: v1alpha1
      kind: KubeControllerManagerConfig
      extraArgs:
        bind-address: "0.0.0.0"
    # Configure kube-scheduler metrics
    - |-
      apiVersion: v1alpha1
      kind: KubeSchedulerConfig
      extraArgs:
        bind-address: "0.0.0.0"
