---
ingress:
  - hostname: "*.${PUBLIC_DOMAIN}"
    service: https://envoy-external.kube-system.svc.cluster.local
    originRequest:
      http2Origin: true
      originServerName: external.${PUBLIC_DOMAIN}
  - service: http_status:404
