---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-secret
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "fda9e7f2-0f6d-4067-ab92-b349013165a1"
    - secretKey: JWT_SECRET
      remoteRef:
        key: "783928df-392a-4ec7-be08-b25b0058752a"
    - secretKey: JS_GEOLITE_LICENSE_KEY
      remoteRef:
        key: "9da192f7-a8b4-4cf9-857f-b34901335ea1"
