---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-secrets
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: SPARKY_DB_PASSWORD
      remoteRef:
        key: "117bc4b9-7615-4657-bda0-b4d20057f999"
    - secretKey: SPARKY_APP_DB_PASSWORD
      remoteRef:
        key: "d35c9517-4ccc-45fa-98f9-b4d20057f9d0"
    - secretKey: SPARKY_API_ENCRYPTION_KEY
      remoteRef:
        key: "f272469d-6497-4d8c-9e83-b4d20057fa02"
    - secretKey: SPARKY_BETTER_AUTH_SECRET
      remoteRef:
        key: "f04592ad-fe74-43fd-90c8-b4d20057fa36"
