---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
## Hooked up to LM Studio on Gaming rig, Ollama annoying me
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - OAUTH_PROVIDER_NAME=Authentik
      - OPENID_PROVIDER_URL=https://auth.mafyuh.io/application/o/open-webui/.well-known/openid-configuration
      - OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET
      - OAUTH_SCOPES=openid email profile
      - OPENID_REDIRECT_URI=https://ai.mafyuh.io/oauth/oidc/callback
      - ENABLE_LOGIN_FORM=false
      - DATABASE_URL=$DATABASE_URL
    extra_hosts:
      - host.docker.internal:host-gateway

  searxng:
    image: searxng/searxng@sha256:a7f9188cc7fa8b6b037e0d85709c0dced8f05d0eba84145eb7fe7027a4c00850
    container_name: searxng
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/searxng:/etc/searxng
    depends_on:
      - open-webui
    restart: unless-stopped
    ports:
      - "8081:8080"

  open-terminal:
    container_name: open-terminal
    image: ghcr.io/open-webui/open-terminal:0.11.34
    restart: unless-stopped
    ports:
      - 3001:8000
    volumes:
      - open-terminal:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=$OPEN_TERMINAL_API_KEY

  mcphub:
    container_name: mcphub
    image: mirror.gcr.io/samanhappy/mcphub:0.12.12
    restart: unless-stopped
    ports:
      - 3003:3000
    environment:
      - ADMIN_PASSWORD=$MCPHUB_ADMIN_PASSWORD
    volumes:
      - ./mcp_settings.json:/app/mcp_settings.json:rw

volumes:
  open-webui:
  open-terminal: