---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatus-chart
spec:
  interval: 2h
  url: https://twin.github.io/helm-charts
