---
# yaml-language-server: $schema=https://schemas.iac.gg/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: unifi-dns-secret
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: "6ef16a27-4629-49c5-85f4-b48500134ac9"
