name: OpenTofu Automation

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: mafyuh/ansible-bws:1.1.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get Secrets from Bitwarden
        id: bitwarden-secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            2dae51bd-bd65-474c-971c-b20800f22afa > aws_access_key_id
            287c852d-f2b5-467d-bfc4-b20800f25f52 > aws_secret_access_key
            3b222376-ccd9-4f44-a4b4-b222001af68a > grafana_auth
            030fbb6a-3b6d-40dc-9c26-b222001b0fb6 > grafana_url
            f8f85ab2-5f6d-46a7-9e06-b20800076d26 > s3_endpoint
            4dff237e-93ad-4eda-a776-b28400653181 > bws_access_token
            efd2db8f-4cb2-4031-ac2d-b2a500447bf4 > oci_private_key

      
      - name: Create tfvars file
        working-directory: ./terraform
        run: |
          cat <<EOF > terraform.tfvars
          s3_endpoint = "${{ steps.bitwarden-secrets.outputs.s3_endpoint }}"
          access_token = "${{ steps.bitwarden-secrets.outputs.bws_access_token }}"
          EOF

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1.0.6

      - name: Run OpenTofu Init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.bitwarden-secrets.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.bitwarden-secrets.outputs.aws_secret_access_key }}
        run: |
          tofu init -var-file=terraform.tfvars


      - name: Run OpenTofu Plan
        id: plan
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.bitwarden-secrets.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.bitwarden-secrets.outputs.aws_secret_access_key }}
          BWS_ACCESS_TOKEN: ${{ secrets.BW_ACCESS_TOKEN }}
        run: tofu plan -parallelism=4 -out=tfplan

      - name: Apply the Plan
        if: success()
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.bitwarden-secrets.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.bitwarden-secrets.outputs.aws_secret_access_key }}
          BWS_ACCESS_TOKEN: ${{ secrets.BW_ACCESS_TOKEN }}
        run: tofu apply tfplan
