---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: open-webui
  values:
    ollama:
      enabled: false
    pipelines:
      enabled: false
    tika:
      enabled: false
    terminals:
      enabled: false
    workload:
      kind: Deployment
    image:
      repository: ghcr.io/open-webui/open-webui
      tag: v0.10.2
      pullPolicy: "IfNotPresent"
      useSlim: true
    route:
      enabled: true
      hostnames: ["chat.mafyuh.dev"]
      parentRefs:
        - name: envoy-external
          namespace: kube-system
          sectionName: https
    persistence:
      enabled: true
      accessMode:
        - ReadWriteOnce
      size: 5Gi
      storageClass: ceph-block
    enableOpenaiApi: true
    openaiBaseApiUrls:
      - "https://integrate.api.nvidia.com/v1"
      - "https://openrouter.ai/api/v1"
      - "http://cli-proxy-api.ai.svc.cluster.local:8317/v1"
    openaiApiKeysExistingSecret: "open-webui-secrets"
    openaiApiKeysExistingSecretKey: "OPENAI_API_KEYS"
    databaseUrl: "${DATABASE_URL}"
    sso:
      enabled: true
      enableSignup: true
      mergeAccountsByEmail: true
      oidc:
        enabled: true
        providerName: "Authentik"
        providerUrl: "https://auth.mafyuh.io/application/o/open-webui/.well-known/openid-configuration"
        scopes: "openid email profile"
        clientExistingSecret: "open-webui-secrets"
        clientIdExistingSecretKey: "OAUTH_CLIENT_ID"
        clientExistingSecretKey: "OAUTH_CLIENT_SECRET"
    extraEnvVars:
      - name: ENABLE_LOGIN_FORM
        value: "false"
      - name: OPENID_REDIRECT_URI
        value: "https://chat.mafyuh.dev/oauth/oidc/callback"
      - name: OAUTH_AUTO_REDIRECT
        value: "true"
